### **ASOCIACION**

In [4]:
import warnings
warnings.filterwarnings('ignore')

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

**Cargar librerías**

In [1]:
import pandas as pd
import numpy as np

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

**Cargar el CSV**

In [5]:
url = "https://raw.githubusercontent.com/MarvinAntillon97/Parcial4_AntillonMarvin_2533222022/refs/heads/main/Archivos/clave_E_asociacion.csv"

df = pd.read_csv(url)

df.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,E-T0001,E-C0068,2026-01-01,Tecnico,Calculadora,1,App
1,E-T0001,E-C0068,2026-01-01,Libros,Novela,1,App
2,E-T0001,E-C0068,2026-01-01,Arte,Pinceles,1,App
3,E-T0001,E-C0068,2026-01-01,Tecnico,Regla,1,App
4,E-T0002,E-C0056,2026-01-22,Papeleria,Lapiz,1,Web

**Estructura del dataset**

In [6]:
print(df.shape)

print(df.columns)

print(df.info())

(605, 7)
Index(['transaccion_id', 'cliente_id', 'fecha', 'categoria', 'item',
       'cantidad', 'canal'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaccion_id  605 non-null    object
 1   cliente_id      605 non-null    object
 2   fecha           605 non-null    object
 3   categoria       605 non-null    object
 4   item            605 non-null    object
 5   cantidad        605 non-null    int64
 6   canal           604 non-null    object
dtypes: int64(1), object(6)
memory usage: 33.2+ KB
None

In [7]:
print(df.isnull().sum())

print(df.duplicated().sum())

transaccion_id    0
cliente_id        0
fecha             0
categoria         0
item              0
cantidad          0
canal             1
dtype: int64
1

In [8]:
df.head()

,transaccion_id,cliente_id,fecha,categoria,item,cantidad,canal
0,E-T0001,E-C0068,2026-01-01,Tecnico,Calculadora,1,App
1,E-T0001,E-C0068,2026-01-01,Libros,Novela,1,App
2,E-T0001,E-C0068,2026-01-01,Arte,Pinceles,1,App
3,E-T0001,E-C0068,2026-01-01,Tecnico,Regla,1,App
4,E-T0002,E-C0056,2026-01-22,Papeleria,Lapiz,1,Web

# **Crear matriz de transacciones**

In [9]:
basket = (
    df.groupby(['transaccion_id', 'item'])['cantidad']
    .sum()
    .unstack()
    .fillna(0)
)

basket.head()

item,Acuarelas,Borrador,Calculadora,Cartulina,Clips,Compas,Cuaderno,Diccionario,Engrapadora,Folder,Lapicero,Lapiz,Libro_matematica,Libro_programacion,Marcadores,Memoria_USB,Novela,Pinceles,Regla,Resaltador
transaccion_id,,,,,,,,,,,,,,,,,,,,
E-T0001,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
E-T0002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
E-T0003,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
E-T0004,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
E-T0005,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0

# **Convertir cantidades a booleanos**

In [10]:
basket_sets = basket.applymap(lambda x: 1 if x > 0 else 0)

basket_sets.head()

item,Acuarelas,Borrador,Calculadora,Cartulina,Clips,Compas,Cuaderno,Diccionario,Engrapadora,Folder,Lapicero,Lapiz,Libro_matematica,Libro_programacion,Marcadores,Memoria_USB,Novela,Pinceles,Regla,Resaltador
transaccion_id,,,,,,,,,,,,,,,,,,,,
E-T0001,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0
E-T0002,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0
E-T0003,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
E-T0004,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
E-T0005,0,0,0,1,1,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0

# **Aplicar algoritmo Apriori**

In [11]:
frequent_items = apriori(
    basket_sets,
    min_support=0.05,
    use_colnames=True
)

frequent_items.sort_values(by='support', ascending=False).head(10)

     support              itemsets
18  0.248649               (Regla)
13  0.243243  (Libro_programacion)
15  0.232432         (Memoria_USB)
6   0.232432            (Cuaderno)
2   0.232432         (Calculadora)
10  0.227027            (Lapicero)
17  0.216216            (Pinceles)
0   0.200000           (Acuarelas)
19  0.167568          (Resaltador)
4   0.162162               (Clips)

# **Generar reglas de asociación**

In [12]:
rules = association_rules(
    frequent_items,
    metric="lift",
    min_threshold=1
)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Acuarelas),(Pinceles),0.200000,0.216216,0.135135,0.675676,3.125000,1.0,0.091892,2.416667,0.850000,0.480769,0.586207,0.650338
1,(Pinceles),(Acuarelas),0.216216,0.200000,0.135135,0.625000,3.125000,1.0,0.091892,2.133333,0.867586,0.480769,0.531250,0.650338
2,(Calculadora),(Regla),0.232432,0.248649,0.124324,0.534884,2.151163,1.0,0.066530,1.615405,0.697183,0.348485,0.380960,0.517442
3,(Regla),(Calculadora),0.248649,0.232432,0.124324,0.500000,2.151163,1.0,0.066530,1.535135,0.712230,0.348485,0.348592,0.517442
4,(Clips),(Libro_programacion),0.162162,0.243243,0.054054,0.333333,1.370370,1.0,0.014609,1.135135,0.322581,0.153846,0.119048,0.277778

**Mostrar las 10 reglas más relevantes**

In [13]:
top_rules = rules.sort_values(
    by='lift',
    ascending=False
)

top_rules[
    [
        'antecedents',
        'consequents',
        'support',
        'confidence',
        'lift'
    ]
].head(10)

,antecedents,consequents,support,confidence,lift
14,"(Lapicero, Cuaderno)",(Resaltador),0.091892,0.850000,5.072581
19,(Resaltador),"(Lapicero, Cuaderno)",0.091892,0.548387,5.072581
15,"(Lapicero, Resaltador)",(Cuaderno),0.091892,0.809524,3.482835
18,(Cuaderno),"(Lapicero, Resaltador)",0.091892,0.395349,3.482835
16,"(Cuaderno, Resaltador)",(Lapicero),0.091892,0.772727,3.403680
17,(Lapicero),"(Cuaderno, Resaltador)",0.091892,0.404762,3.403680
1,(Pinceles),(Acuarelas),0.135135,0.625000,3.125000
0,(Acuarelas),(Pinceles),0.135135,0.675676,3.125000
9,(Resaltador),(Cuaderno),0.118919,0.709677,3.053263
8,(Cuaderno),(Resaltador),0.118919,0.511628,3.053263